volumes:
  redis_data:
  pg_data:

services:
  redis:
    image: redis:latest
    container_name: redis-container
    command: redis-server --appendonly yes --save 60 1 --dir /data
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    restart: unless-stopped
  db:
    image: postgres:17
    container_name: postgresql-container
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped