# Generated by Django 5.1.4 on 2024-12-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3, unique=True, verbose_name='Название валюты')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата запроса курса')),
                ('rates', models.JSONField(default=dict, verbose_name='Запрос курсов валют')),
            ],
            options={
                'verbose_name': 'История валют',
                'verbose_name_plural': 'Истории валют',
                'ordering': ('name',),
                'constraints': [models.UniqueConstraint(fields=('name', 'date'), name='unique_currency')],
            },
        ),
    ]
